require:
  - rubocop-rspec
  - rubocop-rails
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.1.2
  NewCops: enable
  Exclude:
    - db/schema.rb
    - bin/**/*
    - vendor/**/*

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false