version: 2.1

orbs:
  ruby: circleci/ruby@1.4.0

executors:
  default-executor:
    docker:
      - image: cimg/ruby:3.1.2

jobs:
  build:
    executor: default-executor
    steps:
      - checkout
      - restore_cache:
          key: circlev2-{{ checksum "Gemfile.lock" }}
      - run: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - save_cache:
          key: circlev2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
  lefthook:
    executor: default-executor
    steps:
      - run:
          name: Run lefthook
          command: bundle exec lefthook run pre-commit

workflows:
  linters:
    jobs:
      - build
      - lefthook
