version: 2.1

orbs:
  ruby: circleci/ruby@1.4.0

jobs:
  build:
    docker:
      - image: cimg/ruby:3.1.2
    steps:
      - checkout
      - ruby/install-deps

  lefthook:
    docker:
      - image: cimg/ruby:3.1.2
    steps:
      - run: bundle exec lefthook run pre-commit
  
  test:
    docker:
      - image: cimg/ruby:3.1.2
    steps:
      - ruby/rspec-test

workflows:
  linters:
    jobs:
      - build
      - lefthook:
          requires:
            - build
      - test:
          requires:
            - build
