version: 2.1

jobs:
  build:
    docker:
      - image: cimg/ruby:3.1.2
    steps:
      - checkout
      - restore_cache:
          key: circlev2-{{ checksum "Gemfile.lock" }}
      - run: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
      # Store bundle cache
      - save_cache:
          key: circlev2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

  lefthook:
    docker:
      - image: cimg/ruby:3.1.2
    steps:
      - run: bundle exec lefthook run pre-commit
  
  test:
    docker:
      - image: cimg/ruby:3.1.2
    steps:
      - run: bundle exec rspec

workflows:
  linters:
    jobs:
      - build
      - lefthook:
          requires:
            - build
      - test:
          requires:
            - build
