version: 2.1

orbs:
  ruby: circleci/ruby@1.4.0

jobs:
  build:
    docker:
      - image: cimg/ruby:3.1.2
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - bundle-install
  lefthook:
    docker:
      - image: cimg/ruby:3.1.2
    executor: ruby/default
    steps:
      - bundle exec run pre-commit

workflows:
  linters:
    jobs:
      - build
      - lefthook
